name: Setup Java and Gradle

inputs:
  java-version:
    description: 'Java version'
    required: true
  java-distribution:
    description: 'Java distribution'
    required: true
  config:
    description: 'Path to config JSON file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Load Config
      id: config
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        script: |
          const fs = require('fs');
          const config = JSON.parse(fs.readFileSync('${{ inputs.config }}', 'utf8'));
          core.setOutput('java-version', config.java.version);
          core.setOutput('java-distribution', config.java.distribution);
    - name: Setup Java (${{ inputs.java-distribution }} ${{ inputs.java-version }})
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
    - name: Run chmod to make gradlew executable
      shell: bash
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
