name: Reusable Analyze
on:
  workflow_call:
    inputs:
      config:
        description: 'Path to config JSON file'
        type: string
        default: '.github/java-gradle.json'
      name:
        type: string
      task:
        description: 'Gradle task'
        type: string
        required: true
      sarif_file:
        type: string
      category:
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze ${{ inputs.name || inputs.task }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@main
        with:
          config: ${{ inputs.config }}
      - name: 🔍️Run analyze ${{ inputs.name || inputs.task }}
        run: ./gradlew ${{ inputs.task }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@9e0d7b8d25671d64c341c19c0152d693099fb5ba #v4.35.5
        if: ${{ !cancelled() && inputs.sarif_file && inputs.category }}
        with:
          sarif_file: ${{ inputs.sarif_file }}
          category: ${{ inputs.category }}
