name: Reusable Static Code Analysis
on:
  workflow_call:

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check if should run
        run: echo "test"
