name: Reusable Android Build
on:
  workflow_call:
    inputs:
      environment:
        type: string
      task:
        type: string
        required: true
      output-path:
        type: string
        required: true
      config:
        description: 'Path to config JSON file'
        required: true
        type: string
        default: '.github/java-gradle.json'
    secrets:
      ANDROID_STORE_FILE_BASE64:
        required: true
      ANDROID_STORE_PASSWORD:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEY_PASSWORD:
        required: true
jobs:
  android-build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Load Configuration
        id: config
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fs = require('fs');
            const config = JSON.parse(fs.readFileSync('${{ inputs.config }}', 'utf8'));
            core.setOutput('java-version', config.java.version);
            core.setOutput('java-distribution', config.java.distribution);
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle
        with:
          java-version: ${{ steps.config.outputs.java-version }}
          distribution: ${{ steps.config.outputs.java-distribution }}
      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@v2
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
      - name: Run bundleRelease
        run: ./gradlew ${{ inputs.task }}
        env:
          ORG_GRADLE_PROJECT_androidSigningStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Upload AAB to Internal App Sharing
        uses: actions/upload-artifact@v7
        with:
          name: android
          path: ${{ inputs.output-path }}
