name: Reusable Static Code Analysis
on:
  workflow_call:
    inputs:
      analysis-matrix:
        description: >
          JSON array of objects with { task, sarif_file, category } for each analysis run.
        type: string
        required: true
      java-version:
        description: 'Java version'
        type: number
        required: true
        default: 21
      java-distribution:
        description: 'Java distribution'
        type: string
        required: true
        default: 'temurin'

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    name: Analysis ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.analysis-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
      - name: 🔍️Run analysis
        run: ./gradlew ${{ matrix.task }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ !cancelled() && matrix.sarif_file != '' && matrix.sarif_file != null }}
        with:
          sarif_file: ${{ matrix.sarif_file }}
          category: ${{ matrix.category }}
